### PR TITLE
Fixed sample data for our local DB

### PR DESCRIPTION
**Pull request by ld357**
Fixed sample data for our local DB so that everything matches now, with valid lat/lon values!

ORDER OF RESTAURANTS:
Gyu-Kaku at 888 Nelson St g3, Vancouver, BC V6Z 2H1
McDonalds at 2909 Grandview Hwy, Vancouver, BC V5M 2E4
Chipotle at 818 Howe St, Vancouver, BC V6Z 1N4
Ginger at 9100 Blundell Rd #490, Richmond, BC
Yi Fang at 4329 Dawson St, Burnaby, BC V5C 0J8
Tap & Barrel at 75 Athletes Way, Vancouver, BC V5Y 0B1
Marutama Ramen at 270 Robson St, Vancouver, BC V6B 0E7
Sushi Mura at 6485 Oak St, Vancouver, BC V6M 2W7

### CODE REVIEW

**Comment by ericrkuo** [comment]
Looks good, could you run this branch and double check in the FE when clicking on the restaurant cards for each promo that the restaurants show up as expected?

**Comment by ericrkuo** [comment]
Just as a sanity check 😅

**Review by yunishimura0716 — APPROVED** [review]
thank you for your job. I'm just looking the piece of code, and it should have no problem.

**Comment by ericrkuo** [comment]
I think there is a lint warning, let's fix that!

**Review by ericrkuo — APPROVED** [review]

**Pull request merged**
